http:
  port: 8080
secret:
  value: "passhash"
database: "production"
redis:
  host: "localhost"
  port: 6379
  password: ""
  db: 0
facebook:
  appid: ""
  secret: ""
share:
  host: ""
  port: ""
timetable:
  host: ""
  port: ""
weather:
  key: ""
